# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/cmcnally/Repos/mai_project/Vivado/pwm_servo_control/PYNQ-Z2_v1.0.xdc

# Block Designs: bd/pwm_servo/pwm_servo.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pwm_servo || ORIG_REF_NAME==pwm_servo} -quiet] -quiet

# IP: bd/pwm_servo/ip/pwm_servo_processing_system7_0_0/pwm_servo_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pwm_servo_processing_system7_0_0 || ORIG_REF_NAME==pwm_servo_processing_system7_0_0} -quiet] -quiet

# IP: bd/pwm_servo/ip/pwm_servo_axi_timer_0_0/pwm_servo_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pwm_servo_axi_timer_0_0 || ORIG_REF_NAME==pwm_servo_axi_timer_0_0} -quiet] -quiet

# IP: bd/pwm_servo/ip/pwm_servo_xbar_0/pwm_servo_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pwm_servo_xbar_0 || ORIG_REF_NAME==pwm_servo_xbar_0} -quiet] -quiet

# IP: bd/pwm_servo/ip/pwm_servo_ps7_0_axi_periph_0/pwm_servo_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pwm_servo_ps7_0_axi_periph_0 || ORIG_REF_NAME==pwm_servo_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/pwm_servo/ip/pwm_servo_rst_ps7_0_100M_0/pwm_servo_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pwm_servo_rst_ps7_0_100M_0 || ORIG_REF_NAME==pwm_servo_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/pwm_servo/ip/pwm_servo_axi_timer_1_0/pwm_servo_axi_timer_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pwm_servo_axi_timer_1_0 || ORIG_REF_NAME==pwm_servo_axi_timer_1_0} -quiet] -quiet

# IP: bd/pwm_servo/ip/pwm_servo_axi_timer_2_0/pwm_servo_axi_timer_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pwm_servo_axi_timer_2_0 || ORIG_REF_NAME==pwm_servo_axi_timer_2_0} -quiet] -quiet

# IP: bd/pwm_servo/ip/pwm_servo_axi_timer_3_0/pwm_servo_axi_timer_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pwm_servo_axi_timer_3_0 || ORIG_REF_NAME==pwm_servo_axi_timer_3_0} -quiet] -quiet

# IP: bd/pwm_servo/ip/pwm_servo_xlconcat_0_0/pwm_servo_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pwm_servo_xlconcat_0_0 || ORIG_REF_NAME==pwm_servo_xlconcat_0_0} -quiet] -quiet

# IP: bd/pwm_servo/ip/pwm_servo_auto_pc_0/pwm_servo_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pwm_servo_auto_pc_0 || ORIG_REF_NAME==pwm_servo_auto_pc_0} -quiet] -quiet

# XDC: bd/pwm_servo/pwm_servo_ooc.xdc
