webtalk_init -webtalk_dir /home/cmcnally/Repos/robotic-arm-control-system-analysis/vivado/lidar_arm_control/hardware_offload_system/hardware_system.sdk/webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2021-04-12 23:52:01" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2018.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2018.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "oufh7mvt045l9rma3uprjd77dq" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2018.3_40" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "40" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 18.04.5 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2700.057 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.259 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1618265708000" -context "sdk\\\\hardware/1618265708000"
webtalk_add_data -client sdk -key isZynq -value "true" -context "sdk\\\\hardware/1618265708000"
webtalk_add_data -client sdk -key isZynqMP -value "false" -context "sdk\\\\hardware/1618265708000"
webtalk_add_data -client sdk -key Processors -value "2" -context "sdk\\\\hardware/1618265708000"
webtalk_add_data -client sdk -key VivadoVersion -value "2018.3" -context "sdk\\\\hardware/1618265708000"
webtalk_add_data -client sdk -key Arch -value "zynq" -context "sdk\\\\hardware/1618265708000"
webtalk_add_data -client sdk -key Device -value "7z020" -context "sdk\\\\hardware/1618265708000"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1618265708000"
webtalk_add_data -client sdk -key os -value "NA" -context "sdk\\\\hardware/1618265708000"
webtalk_add_data -client sdk -key apptemplate -value "NA" -context "sdk\\\\hardware/1618265708000"
webtalk_add_data -client sdk -key RecordType -value "HWCreation" -context "sdk\\\\hardware/1618265708000"
webtalk_add_data -client sdk -key uid -value "1618265921000" -context "sdk\\\\bsp/1618265921000"
webtalk_add_data -client sdk -key hwid -value "1618265708000" -context "sdk\\\\bsp/1618265921000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1618265921000"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\bsp/1618265921000"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1618265921000"
webtalk_add_data -client sdk -key uid -value "1618265922000" -context "sdk\\\\application/1618265922000"
webtalk_add_data -client sdk -key hwid -value "1618265708000" -context "sdk\\\\application/1618265922000"
webtalk_add_data -client sdk -key bspid -value "1618265921000" -context "sdk\\\\application/1618265922000"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1618265922000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1618265922000"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\application/1618265922000"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1618265922000"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1618265922000"
webtalk_add_data -client sdk -key Procused -value "ps7_cortexa9" -context "sdk\\\\application/1618265922000"
webtalk_add_data -client sdk -key projSize -value "324.55859375" -context "sdk\\\\application/1618265922000"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1618267921254"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1618267921254"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1618267921254"
webtalk_add_data -client sdk -key DebugCount -value "1" -context "sdk\\\\bsp/1618267921254"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1618267921254"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1618267921254"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1618267921254"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1618267921254"
webtalk_transmit -clientid 2322666009 -regid "" -xml /home/cmcnally/Repos/robotic-arm-control-system-analysis/vivado/lidar_arm_control/hardware_offload_system/hardware_system.sdk/webtalk/usage_statistics_ext_sdk.xml -html /home/cmcnally/Repos/robotic-arm-control-system-analysis/vivado/lidar_arm_control/hardware_offload_system/hardware_system.sdk/webtalk/usage_statistics_ext_sdk.html -wdm /home/cmcnally/Repos/robotic-arm-control-system-analysis/vivado/lidar_arm_control/hardware_offload_system/hardware_system.sdk/webtalk/sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
