# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/cmcnally/Repos/robotic-arm-control-system-analysis/vivado/lidar_arm_control/freertos_system/PYNQ-Z2_v1.0.xdc

# Block Designs: bd/lidar_arm_control/lidar_arm_control.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lidar_arm_control || ORIG_REF_NAME==lidar_arm_control} -quiet] -quiet

# IP: bd/lidar_arm_control/ip/lidar_arm_control_processing_system7_0_0/lidar_arm_control_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lidar_arm_control_processing_system7_0_0 || ORIG_REF_NAME==lidar_arm_control_processing_system7_0_0} -quiet] -quiet

# IP: bd/lidar_arm_control/ip/lidar_arm_control_axi_timer_0_0/lidar_arm_control_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lidar_arm_control_axi_timer_0_0 || ORIG_REF_NAME==lidar_arm_control_axi_timer_0_0} -quiet] -quiet

# IP: bd/lidar_arm_control/ip/lidar_arm_control_axi_timer_1_0/lidar_arm_control_axi_timer_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lidar_arm_control_axi_timer_1_0 || ORIG_REF_NAME==lidar_arm_control_axi_timer_1_0} -quiet] -quiet

# IP: bd/lidar_arm_control/ip/lidar_arm_control_axi_timer_2_0/lidar_arm_control_axi_timer_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lidar_arm_control_axi_timer_2_0 || ORIG_REF_NAME==lidar_arm_control_axi_timer_2_0} -quiet] -quiet

# IP: bd/lidar_arm_control/ip/lidar_arm_control_axi_timer_3_0/lidar_arm_control_axi_timer_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lidar_arm_control_axi_timer_3_0 || ORIG_REF_NAME==lidar_arm_control_axi_timer_3_0} -quiet] -quiet

# IP: bd/lidar_arm_control/ip/lidar_arm_control_xbar_0/lidar_arm_control_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lidar_arm_control_xbar_0 || ORIG_REF_NAME==lidar_arm_control_xbar_0} -quiet] -quiet

# IP: bd/lidar_arm_control/ip/lidar_arm_control_ps7_0_axi_periph_0/lidar_arm_control_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lidar_arm_control_ps7_0_axi_periph_0 || ORIG_REF_NAME==lidar_arm_control_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/lidar_arm_control/ip/lidar_arm_control_rst_ps7_0_100M_0/lidar_arm_control_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lidar_arm_control_rst_ps7_0_100M_0 || ORIG_REF_NAME==lidar_arm_control_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/lidar_arm_control/ip/lidar_arm_control_axi_uartlite_0_0/lidar_arm_control_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lidar_arm_control_axi_uartlite_0_0 || ORIG_REF_NAME==lidar_arm_control_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/lidar_arm_control/ip/lidar_arm_control_xlconcat_0_1/lidar_arm_control_xlconcat_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lidar_arm_control_xlconcat_0_1 || ORIG_REF_NAME==lidar_arm_control_xlconcat_0_1} -quiet] -quiet

# IP: bd/lidar_arm_control/ip/lidar_arm_control_axi_gpio_0_0/lidar_arm_control_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lidar_arm_control_axi_gpio_0_0 || ORIG_REF_NAME==lidar_arm_control_axi_gpio_0_0} -quiet] -quiet

# IP: bd/lidar_arm_control/ip/lidar_arm_control_auto_pc_0/lidar_arm_control_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lidar_arm_control_auto_pc_0 || ORIG_REF_NAME==lidar_arm_control_auto_pc_0} -quiet] -quiet

# XDC: bd/lidar_arm_control/lidar_arm_control_ooc.xdc
