# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/cmcnally/Repos/mai_project/Vivado/ultrasonic_sensors/ultrasonic_sensors.srcs/sources_1/bd/ultrasonic_unit/ip/ultrasonic_unit_auto_pc_0/ultrasonic_unit_auto_pc_0.xci
# IP: The module: 'ultrasonic_unit_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/cmcnally/Repos/mai_project/Vivado/ultrasonic_sensors/ultrasonic_sensors.srcs/sources_1/bd/ultrasonic_unit/ip/ultrasonic_unit_auto_pc_0/ultrasonic_unit_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ultrasonic_unit_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/cmcnally/Repos/mai_project/Vivado/ultrasonic_sensors/ultrasonic_sensors.srcs/sources_1/bd/ultrasonic_unit/ip/ultrasonic_unit_auto_pc_0/ultrasonic_unit_auto_pc_0.xci
# IP: The module: 'ultrasonic_unit_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/cmcnally/Repos/mai_project/Vivado/ultrasonic_sensors/ultrasonic_sensors.srcs/sources_1/bd/ultrasonic_unit/ip/ultrasonic_unit_auto_pc_0/ultrasonic_unit_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ultrasonic_unit_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
