# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/cmcnally/Repos/mai_project/Vivado/ultrasonic_sensors/PYNQ-Z2_v1.0.xdc

# Block Designs: bd/ultrasonic_unit/ultrasonic_unit.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultrasonic_unit || ORIG_REF_NAME==ultrasonic_unit} -quiet] -quiet

# IP: bd/ultrasonic_unit/ip/ultrasonic_unit_processing_system7_0_0/ultrasonic_unit_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultrasonic_unit_processing_system7_0_0 || ORIG_REF_NAME==ultrasonic_unit_processing_system7_0_0} -quiet] -quiet

# IP: bd/ultrasonic_unit/ip/ultrasonic_unit_axi_gpio_0_0/ultrasonic_unit_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultrasonic_unit_axi_gpio_0_0 || ORIG_REF_NAME==ultrasonic_unit_axi_gpio_0_0} -quiet] -quiet

# IP: bd/ultrasonic_unit/ip/ultrasonic_unit_auto_pc_0/ultrasonic_unit_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultrasonic_unit_auto_pc_0 || ORIG_REF_NAME==ultrasonic_unit_auto_pc_0} -quiet] -quiet

# IP: bd/ultrasonic_unit/ip/ultrasonic_unit_ps7_0_axi_periph_0/ultrasonic_unit_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultrasonic_unit_ps7_0_axi_periph_0 || ORIG_REF_NAME==ultrasonic_unit_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/ultrasonic_unit/ip/ultrasonic_unit_rst_ps7_0_100M_0/ultrasonic_unit_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultrasonic_unit_rst_ps7_0_100M_0 || ORIG_REF_NAME==ultrasonic_unit_rst_ps7_0_100M_0} -quiet] -quiet

# XDC: bd/ultrasonic_unit/ultrasonic_unit_ooc.xdc
