# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/cmcnally/Repos/mai_project/Vivado/us_arm_control/us_arm_control.srcs/sources_1/bd/us_arm_control/ip/us_arm_control_axi_gpio_0_0/us_arm_control_axi_gpio_0_0.xci
# IP: The module: 'us_arm_control_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/cmcnally/Repos/mai_project/Vivado/us_arm_control/us_arm_control.srcs/sources_1/bd/us_arm_control/ip/us_arm_control_axi_gpio_0_0/us_arm_control_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'us_arm_control_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/cmcnally/Repos/mai_project/Vivado/us_arm_control/us_arm_control.srcs/sources_1/bd/us_arm_control/ip/us_arm_control_axi_gpio_0_0/us_arm_control_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'us_arm_control_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/cmcnally/Repos/mai_project/Vivado/us_arm_control/us_arm_control.srcs/sources_1/bd/us_arm_control/ip/us_arm_control_axi_gpio_0_0/us_arm_control_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'us_arm_control_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/cmcnally/Repos/mai_project/Vivado/us_arm_control/us_arm_control.srcs/sources_1/bd/us_arm_control/ip/us_arm_control_axi_gpio_0_0/us_arm_control_axi_gpio_0_0.xci
# IP: The module: 'us_arm_control_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/cmcnally/Repos/mai_project/Vivado/us_arm_control/us_arm_control.srcs/sources_1/bd/us_arm_control/ip/us_arm_control_axi_gpio_0_0/us_arm_control_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'us_arm_control_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/cmcnally/Repos/mai_project/Vivado/us_arm_control/us_arm_control.srcs/sources_1/bd/us_arm_control/ip/us_arm_control_axi_gpio_0_0/us_arm_control_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'us_arm_control_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/cmcnally/Repos/mai_project/Vivado/us_arm_control/us_arm_control.srcs/sources_1/bd/us_arm_control/ip/us_arm_control_axi_gpio_0_0/us_arm_control_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'us_arm_control_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
